### ISSUE TITLE
Not working in npm7 workspaces

### ISSUE THREAD

**Issue by Kvisaz** [VladimirMikulic/parcel-plugin-custom-dist-structure#45] opened 2021-05-18 14:55 UTC
**Describe the bug**
NPM7 workspaces (and some other monorepository tools) use common node_modules in monorepository root

When we start npm run start from module dir - parcel-plugin-custom-dist-structure  try to find node_modules in current folder and fail with error

`Plugin parcel-plugin-custom-dist-structure failed to initialize: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string....`

like in [issue16](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure/issues/16)

**How it happened?**
Use it with monorepository with npm7 workspaces

**Desktop (please complete the following information):**
 - Windows & MacOs

**Plugin configuration object:**
any configuration

**Comment by VladimirMikulic** [comment] 2021-05-18 15:46
@Kvisaz thanks for reporting this. It's indeed strange. Could you please try the plugin in the non-workspace environment just to confirm that it's not a bug related to your setup/my plugin? Thanks!

**Comment by VladimirMikulic** [comment] 2021-05-22 14:04
Closing due to lack of further information. Feel free to comment with more details. Thanks!

**Closed by VladimirMikulic** 2021-05-22 14:04 UTC
Labels: bug
