### ISSUE TITLE
The image path in css doesn't replaced

### ISSUE THREAD

**Issue by BskyRui** [VladimirMikulic/parcel-plugin-custom-dist-structure#29] opened 2020-07-19 13:55 UTC
```css
// css/style.css
background:url(/my_prize.1b440f9c.png);background-size:contain}
```
Actually `my_prize.1b440f9c.png` is in `/images/my_prize.1b440f9c.png`, this is not a right path.

**Comment by VladimirMikulic** [comment] 2020-07-20 08:00
Hi @BskyRui.
Thank you for reporting this issue.

Which version of the plugin are you using and the version of Parcel?
I would like to see your config in package.json as well.

**Comment by BskyRui** [comment] 2020-07-20 10:15
> Hi @BskyRui.
> Thank you for reporting this issue.
> 
> Which version of the plugin are you using and the version of Parcel?
> I would like to see your config in package.json as well.

@VladimirMikulic 

package.json
```json
{
    "name": "fe-t",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "start": "parcel ./src/index.html",
        "build": "rm -rf ./dist && NODE_ENV=prod parcel build ./src/index.html --out-dir ./dist"
    },
    "author": "LR",
    "license": "ISC",
    "devDependencies": {
        "@babel/core": "^7.10.5",
        "babel-plugin-import": "^1.13.0",
        "babel-plugin-module-resolver": "^4.0.0",
        "parcel-bundler": "^1.12.4",
        "parcel-plugin-custom-dist-structure": "^1.1.14",
        "sass": "^1.26.10"
    },
    "customDistStructure": {
        "config": {
            ".css": "css",
            ".js": "js",
            "images": [
                ".jpg",
                ".png"
            ],
            ".fileExtension": "folder/in/dist",
            "folder/in/dist": [
                ".file",
                ".extensions" ]
        }
    }
}

```

**Comment by VladimirMikulic** [comment] 2020-07-20 10:43
Thanks, @BskyRui.
I have used [this repo](https://github.com/clovis-rosa/landingpage_test) which, I think has a similar structure to your project and I wasn't able to reproduce this issue.

Is your project by any chance open-source so I can take a look?
If it's not, could you set up an example repo which reproduces the issue?

**Comment by BskyRui** [comment] 2020-07-21 01:56
@VladimirMikulic Yes, I didn't use `development ` mode because I don't understand what the meaning of this, so I deleted it. I checked  your repo, and the style file doesn't contain `background: url(xxx.png)`. I can make a simple demo, how to send it to you?

**Comment by VladimirMikulic** [comment] 2020-07-21 09:31
@BskyRui the example repo doesn't contain `background: url(xyz.png)`, I've added it locally.
> I can make a simple demo, how to send it to you?
You can simply make it a public repo on your GitHub account and delete it after I fix the issue, or you can upload it to cloud (Dropbox, GDrive etc.)

Whatever works the best for you.

**Comment by BskyRui** [comment] 2020-07-21 13:31
@VladimirMikulic 
I pushed source code to this [repo](https://github.com/BskyRui/parcel-test.git). The `master` branch is the right demo which a DIV with a background image. Another branch used this plugin, the background image path in style file is wrong when `npm run build`.

**Comment by VladimirMikulic** [comment] 2020-07-21 13:33
Thank you very much @BskyRui. I am all over it now!

**Comment by VladimirMikulic** [comment] 2020-07-21 13:50
Alright, I was able to identify the issue. This happens only for CSS imports inside JS that reference external files (i.e. images).
Stay tuned, the fix is coming!

**Comment by AndreaBaccolini** [comment] 2020-08-14 12:26
Hi, no new info for this issue?

**Comment by VladimirMikulic** [comment] 2020-08-14 12:49
Sorry, everyone! I've been busy for the past few weeks. Hopefully, I'll be able to get on this soon.

**Comment by geongeorge** [comment] 2020-08-18 08:10
@VladimirMikulic  Thanks for this project.

Just linking this here :) https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure/issues/31#issuecomment-675328754

**Comment by AndreaBaccolini** [comment] 2020-09-09 14:43
Any news about it? I ask you because it would be very useful. Thx

**Comment by VladimirMikulic** [comment] 2020-09-09 14:48
Hello, @AndreaBaccolini. I appreciate you commenting on the issue.
I was wondering if you have the same problem?

Not related to this discussion, but I would like to warn you that you have misspelt name in your Github profile README. ("bame")
Thanks.

**Comment by AndreaBaccolini** [comment] 2020-09-11 12:52
@VladimirMikulic  Hello yes, I also have the same problem and for now I solve it by putting the images in the folder by hand and changing the address to the link.
As for the name in my README I don't understand what you mean

**Comment by VladimirMikulic** [comment] 2020-09-11 12:56
Thanks, @AndreaBaccolini. I'll see what I can do to it.
[Here is](https://imgur.com/a/dUbif0g) what I meant about the typo in your README.

**Comment by hrahimi270** [comment] 2020-12-09 16:25
Hi @VladimirMikulic.
Any updates on this issue? I'm using the last version of this plugin and having the same issue.

**Comment by VladimirMikulic** [comment] 2020-12-09 19:04
Hi @hrahimi270. Unfortunately, I don't have enough time to get back to this project right now.

**Comment by deivuss331** [comment] 2020-12-11 13:10
Waiting for the fix too.

**Comment by VladimirMikulic** [comment] 2021-03-20 04:32
@AndreaBaccolini  @hrahimi270 @deivuss331 v1.1.17 has been released after so much time haha.
Thank you all for being patient. I have tested it with some of the repos in the linked issue and it seems the linking works correctly now.

Closing this now, but feel free to reopen if it does occur again!

**Closed by VladimirMikulic** 2021-03-20 04:32 UTC
