### ISSUE TITLE
Wrong path of imported image on build

### ISSUE THREAD

**Issue by cooltolia** [VladimirMikulic/parcel-plugin-custom-dist-structure#31] opened 2020-07-21 10:38 UTC
**Describe the bug**
Imported image in js has wrong path after project build

**How it happened?**
Hi. Foremost let me thank you for such great plugin. I wouldn't use parcel without it)
Though I've encountered with one problem

In my js file need no import image.
Do it either in by import or require, result is the same
`import img from '~/assets/images/main-page/map-point.png';`

While in dev mode everything works fine, after build there is wrong path for this image:
`file:///C:/Users/Kulak/Github/assets/images/map-point.b282edbe.png net::ERR_FILE_NOT_FOUND`

All other images have correct paths, for instance:
`file:///C:/Users/Kulak/Github/spbplod/docs/assets/images/big-logo.a8ec112d.svg`

May be I just miss something to make this work for 100%?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Parcel version: 1.12.4
 - Plugin version: 1.1.14

**Plugin configuration object:**
```
"customDistStructure": {
        "config": {
            ".js": "assets/js",
            ".js.map": "assets/js",
            ".css": "assets/css",
            ".css.map": "assets/css",
            "assets/images": [
                ".jpg",
                ".png",
                ".svg"
            ],
            "assets/fonts": [
                ".woff",
                ".woff2",
                ".ttf"
            ],
            ".fileExtension": "folder/in/dist",
            "folder/in/dist": [
                ".file",
                ".extensions"
            ]
        }
    }
```

**Comment by VladimirMikulic** [comment] 2020-07-21 13:17
Hi @cooltolia.
I appreciate your kind words.

You are saying that all other image paths are fine, except this `map-point.png` image?
Is your repo by any chance open-source so I can take a look at it?
If it's not, could you please set up the example repo which reproduces this issue.

Lastly, could you verify that this persists with version 1.1.13 of the plugin?

Thank you.

**Comment by VladimirMikulic** [comment] 2020-07-21 13:17
Possibly related to #29

**Comment by cooltolia** [comment] 2020-07-21 14:10
@VladimirMikulic 

just tried version 1.1.13. No joy

[Here](https://github.com/cooltolia/spbplod) you may look at the project

**Comment by geongeorge** [comment] 2020-08-18 08:09
Same issue here!
```
"images": [
        ".jpg",
        ".png"
      ]
```
The png is placed in the `images` directory.
But the css `url()` import points to `/file.png` (instead of `/images/file.png`)

**Comment by VladimirMikulic** [comment] 2020-08-18 09:06
Thanks, @geongeorge for reporting this.
Could you please set up an example repo that reproduces this issue?
Does this occur in production build only or in the development as well?

Lastly, what is your OS?

**Comment by geongeorge** [comment] 2020-08-19 11:09
@VladimirMikulic 
This is not a full repo but use this repo: https://github.com/geongeorge/Awesome-Sass-Tailwind-Parcel-Boilerplate
- Add an image in images folder
- Add the settings to config
```
"images": [
        ".jpg",
        ".png"
      ]
```
- Set it as background using css
```css
background: url(../images/file.jpg);
```
- It will work in dev server
but if you build it the images will be placed in the root


Also, my os is Mac OS Catalina

**Comment by chinoto** [comment] 2020-10-04 06:41
I believe I'm having the same issue, but I'm trying to use relative paths via `--public-url ./`. Here is my MRE: https://github.com/chinoto/parcel_custom_structure_bug_mre

All source files are at the same level. `index.html` fetches `app.js`, which imports `example.jpg`. These are the paths they try to use after compiling and what I am expecting to see. The only one that works is `app.js` when using `--public-url ./`.

| `--public-url` | `app.js`                 | `example.jpg`                      |
| -------------- | ------------------------ | ---------------------------------- |
| `./`           | `js/app.d05ddeb8.js`     | `../images/example.ace2ed77.jpg` |
| `.`            | `app.d05ddeb8.js`        | `example.ace2ed77.jpg`           |
| expected       | `./js/app.d05ddeb8.js`   | `./images/example.ace2ed77.jpg`  |

**Comment by VladimirMikulic** [comment] 2021-03-20 04:30
@geongeorge v1.1.17 has been released with amazing work by @jamiegluk. I just tested it with the repo you specified and the issue is resolved!

**Closed by VladimirMikulic** 2021-03-20 04:30 UTC
Labels: bug
