### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by jhess666** [VladimirMikulic/parcel-plugin-custom-dist-structure#32] opened 2020-07-22 21:31 UTC
**Describe the bug**

DevTools can't parse generated source maps.

**How it happened?**

The error is pretty much trivial and happens because of the path replacements (probably only for Windows).

It's easy to identify the reason just looking at the console log.

DevTools error message:
`Unexpected token s in JSON at position 86`

Now, let's take a look at the generated source map file.

The source map JSON:
```json
{"version":3,"sources":[],"names":[],"mappings":"","file":"main.css","sourceRoot":"..\src"}
```

See, the `sourceRoot` value contains a non-escaped string. Should be `"..\\src"`;

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Parcel version: 1.12.4
 - Plugin version: 1.1.14

**Plugin configuration object:**
```json
"customDistStructure": {
  "config": {
    "css": [
      ".css",
      ".css.map"
    ],
    "js": [
      ".js",
      ".js.map"
    ]
  },
  "options": {
    "development": true
  }
}
```

**Comment by VladimirMikulic** [comment] 2020-07-22 21:50
Hi @jhess666. Thank you for reporting this issue.
Do you, by any chance use WSL?

**Comment by jhess666** [comment] 2020-07-22 22:02
Nope. It's a pure Windows environment.

**Comment by VladimirMikulic** [comment] 2020-07-28 16:41
Hi @jhess666.

I have a Windows 7 in VM and I am unable to reproduce the issue. Could you set up an example repo which reproduces this issue? Thanks.

**Comment by jhess666** [comment] 2020-07-28 20:44
In my tests I have found where the issue is being originated (at least for me):

```js
// File: "./lib/Utils.js"

// ...

exports.replaceInFileSync = (files, stringToReplace, newString) => {
  const regexPattern = escapeRegex(stringToReplace);

  const result = replaceInFile.sync({
    files,
    from: new RegExp(regexPattern, 'g'),
    to: newString // <-- here, it should be escaped
  });

  return result;
};

// ...
```

**Comment by VladimirMikulic** [comment] 2020-07-29 09:06
Could please set up an example repo that reproduces this issue? Thanks.

**Comment by VladimirMikulic** [comment] 2020-08-07 21:37
Closing this since I was unable to reproduce the issue. Feel free to comment here and we'll reopen this if it happens again.

**Closed by VladimirMikulic** 2020-08-07 21:37 UTC
Labels: bug
